apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reliability-copilot.fullname" . }}-secrets
  labels:
    {{- include "reliability-copilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.llm.groqApiKey | quote }}
  OPENAI_API_KEY: {{ .Values.llm.openaiApiKey | quote }}
  GEMINI_API_KEY: {{ .Values.llm.geminiApiKey | quote }}
  JWT_SECRET_KEY: {{ .Values.auth.jwtSecretKey | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.alerting.slackWebhookUrl | quote }}
