apiVersion: v1
kind: Service
metadata:
  name: reliability-copilot-frontend
spec:
  type: LoadBalancer
  selector:
    app: reliability-copilot-frontend
  ports:
    - port: 8501
      targetPort: 8501
